### ISSUE TITLE
Make pipelines less special – they're just process()-ables after all

### ISSUE THREAD

**Issue by alexbrasetvik** [foundit/Piped#14]
Everything that currently invokes pipelines might just as well be able to invoke arbitrary dependencies – as long as the depended-on resource quacks to the tune of `process(baton)` – optinally returning `Deferreds`.

This shouldn't be much harder than removing some `pipeline.`-prefixes here and there.

**Comment by nkvoll** [comment]
Closed by https://github.com/foundit/Piped/pull/17
